### ISSUE TITLE
1.9.0_alpha2 crash - Toggle Collapse comment

### ISSUE THREAD

**Issue by hexid** [QuantumBadger/RedReader#239]
```
java.lang.ClassCastException: org.quantumbadger.redreader_alpha_190_2.views.liststatus.SpecificCommentThreadView cannot be cast to org.quantumbadger.redreader_alpha_190_2.reddit.RedditCommentListItem
at org.quantumbadger.redreader_alpha_190_2.fragments.CommentListingFragment.handleCommentVisibilityToggle(CommentListingFragment.java:121)
at org.quantumbadger.redreader_alpha_190_2.fragments.CommentListingFragment.onCommentClicked(CommentListingFragment.java:369)
at org.quantumbadger.redreader_alpha_190_2.views.RedditCommentView.notifyClick(RedditCommentView.java:92)
at com.laurencedawson.activetextview.ActiveTextView$3.onClick(ActiveTextView.java:210)
at android.view.View.performClick(View.java:4789)
at android.view.View$PerformClick.run(View.java:19881)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5293)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

This occurs when toggling a comment that is listed under a specific comment thread.
For example, using `Go to Comment` in the comment menu and then trying to collapse any of the comments listed

Rom: Cyanogenmod 12.1 nightly
Android version: 5.1.1

**Comment by hexid** [comment]
Tested with 0e9efbf9d9106115b1044e5e53a0dfc4efb98bde and this appears to be fixed.

Thanks @QuantumBadger

**Comment by QuantumBadger** [comment]
Excellent -- thanks for testing it!
