### ISSUE TITLE
Crash - Returning from internal browser

### ISSUE THREAD

**Issue by hexid** [QuantumBadger/RedReader#240]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.setTitle(java.lang.CharSequence)' on a null object reference
at org.quantumbadger.redreader_alpha.fragments.WebViewFragment$2.onPageStarted(WebViewFragment.java:190)
at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:547)
at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:144)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5294)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

This crash occurs (randomly?) on the latest master (and in both of the alphas) when returning from the internal browser.

Here's a quick patch that fixes the issue, but I'll try to look into why the `onPageStarted` method is getting called after the activity has been destroyed.

```diff
diff --git a/src/main/java/org/quantumbadger/redreader/fragments/WebViewFragment.java b/src/main/java/org/quantumbadger/redreader/fragments/WebViewFragment.java
index f11df6b..b64fdff 100644
--- a/src/main/java/org/quantumbadger/redreader/fragments/WebViewFragment.java
+++ b/src/main/java/org/quantumbadger/redreader/fragments/WebViewFragment.java
@@ -18,6 +18,7 @@
 package org.quantumbadger.redreader.fragments;

 import android.annotation.SuppressLint;
+import android.app.Activity;
 import android.app.Fragment;
 import android.content.Context;
 import android.graphics.Bitmap;
@@ -187,7 +188,11 @@ public class WebViewFragment extends Fragment implements RedditPostView.PostSele
                                @Override
                                public void onPageStarted(WebView view, String url, Bitmap favicon) {
                                        super.onPageStarted(view, url, favicon);
-                                       getActivity().setTitle(url);
+
+                                       Activity a = getActivity();
+                                       if(a != null) {
+                                               a.setTitle(url);
+                                       }
                                }

                                @Override
```

Rom: Cyanogenmod 12.1 nightly
Android version: 5.1.1

**Comment by QuantumBadger** [comment]
Thanks for the report -- I've added that null check.

If I had to guess, I'd say the WebView is stopping asynchronously when we call pause(), and will continue giving us callbacks until its own threads finish.
