### ISSUE TITLE
Crashes when phone language is set to Arabic

### ISSUE THREAD

**Issue by husadd** [QuantumBadger/RedReader#360]
I always used my phone with English language, for some reason I needed to change my language to Arabic to test something on another app, then I launched Redreader and had a problem. Whenever I click a subreddit it crashes (I tried to choose from pinned subreddits, I think it's the same if I search or choose from subscribed subreddits but not sure). Now I'm using English again but thought I would share so you check out and other people who are using their phones in Arabic (and *probably* other -RTL- languages) won't miss this awesome app :-)

And sure, the specs: Android 6.0, phone: LG G4 not rooted.

**Comment by QuantumBadger** [comment]
Seems to work for me! Do you have a copy of the crash log? (the app saves a .txt file to your /sdcard every time it crashes)

**Comment by husadd** [comment]
android.database.sqlite.SQLiteException: no such column: ٢ (code 1): , while compiling: SELECT id, url, user, session, timestamp, status, type, mimetype FROM web WHERE status=٢ AND url=? AND user=? ORDER BY timestamp DESC
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:893)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:504)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1426)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1273)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1144)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1312)
	at org.quantumbadger.redreader.cache.CacheDbManager.select(CacheDbManager.java:108)
	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.handleRequest(CacheManager.java:371)
	at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread.run(CacheManager.java:337)

I'll also send the txt file to your email in case it's not clear here.

Tried clearing app data and cache but the same happend.
(Maybe the problem is related to the number 2 being in arabic not in english in line 1 and 2)
Also this crash log is from the app without logging in since I tried after clearing app data.

**Comment by QuantumBadger** [comment]
Thanks! I think the issue was due to `String.format` using the default locale, and therefore using Arabic numerals in the SQL query.

https://github.com/QuantumBadger/RedReader/commit/ffd50d1ea1705af52d21682a17e21fe39d794565

Should be fixed in Alpha 65 :)

**Comment by husadd** [comment]
Thanks for your hard work. You're the best :)
