### ISSUE TITLE
Load more comments doesn't work in big posts

### ISSUE THREAD

**Issue by japanesephundroid** [QuantumBadger/RedReader#375]
The last one in a page that loads all the remaining comments that were not loaded on the first page.
I noticed this in the [Matt Damon AMA](https://www.reddit.com/r/IAmA/comments/4tnhf2/i_am_matt_damon_ask_me_anything/) when it was posted about a month ago.
Back then it stopped and restarted the app.

**Comment by QuantumBadger** [comment]
Can confirm, the last one seems to do nothing for me. I'll look at this for 1.9.6.

**Comment by QuantumBadger** [comment]
Looks like Android is unhappy with the number of comment URLs being added to the intent.

Maybe as a quick fix I could modify this to send through only the comment IDs, rather than the entire URLs.

    09-01 20:21:59.544 2833-2833/org.quantumbadger.redreader E/AndroidRuntime: FATAL EXCEPTION: main
       Process: org.quantumbadger.redreader, PID: 2833
       java.lang.RuntimeException: Failure from system
           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
           at android.app.Activity.startActivityForResult(Activity.java:3917)
           at android.app.Activity.startActivityForResult(Activity.java:3877)
           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
           at android.app.Activity.startActivity(Activity.java:4200)
           at android.app.Activity.startActivity(Activity.java:4168)
           at org.quantumbadger.redreader.views.LoadMoreCommentsView$1.onClick(LoadMoreCommentsView.java:109)
           at android.view.View.performClick(View.java:5198)
           at android.view.View$PerformClick.run(View.java:21147)
           at android.os.Handler.handleCallback(Handler.java:739)
           at android.os.Handler.dispatchMessage(Handler.java:95)
           at android.os.Looper.loop(Looper.java:148)
           at android.app.ActivityThread.main(ActivityThread.java:5417)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        Caused by: android.os.TransactionTooLargeException: data parcel size 1198316 bytes
           at android.os.BinderProxy.transactNative(Native Method)
           at android.os.BinderProxy.transact(Binder.java:503)
           at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2657)
           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
           at android.app.Activity.startActivityForResult(Activity.java:3917) 
           at android.app.Activity.startActivityForResult(Activity.java:3877) 
           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842) 
           at android.app.Activity.startActivity(Activity.java:4200) 
           at android.app.Activity.startActivity(Activity.java:4168) 
           at org.quantumbadger.redreader.views.LoadMoreCommentsView$1.onClick(LoadMoreCommentsView.java:109) 
           at android.view.View.performClick(View.java:5198) 
           at android.view.View$PerformClick.run(View.java:21147) 
           at android.os.Handler.handleCallback(Handler.java:739) 
           at android.os.Handler.dispatchMessage(Handler.java:95) 
           at android.os.Looper.loop(Looper.java:148) 
           at android.app.ActivityThread.main(ActivityThread.java:5417) 
           at java.lang.reflect.Method.invoke(Native Method) 
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by QuantumBadger** [comment]
Fixed:

https://github.com/QuantumBadger/RedReader/commit/7c07d7b217b11b9869b3041f9aa76f2679f9ea58

Should be in Alpha 75 :)

**Comment by japanesephundroid** [comment]
Thanks man, I tested the Alpha now, it works :)
