### ISSUE TITLE
Crash during commenting

### ISSUE THREAD

**Issue by philipwhiuk** [QuantumBadger/RedReader#467]
```
03-21 12:30:30.317 15386-15386/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.quantumbadger.redreader, PID: 15386
                                                   java.lang.IllegalArgumentException: View=DecorView@51ad0f5[Submitting…] not attached to window manager
                                                       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
                                                       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
                                                       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
                                                       at android.app.Dialog.dismissDialog(Dialog.java:370)
                                                       at android.app.Dialog.dismiss(Dialog.java:353)
                                                       at org.quantumbadger.redreader.activities.CommentEditActivity$3$1.run(CommentEditActivity.java:128)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

Android version: 7.1.2 (Beta) - Nexus 6P - BuildNPG47I
RedReader version: 1.9.7

**Comment by QuantumBadger** [comment]
Thanks for the report. Looks like Android now throws an exception if the activity owning a dialog is closed before the dialog itself.

I've put in a fix here which ignores the exception: https://github.com/QuantumBadger/RedReader/commit/38a3b66e4ba9ccfcf47c0a2ce357d6e7692a5dcc
