### ISSUE TITLE
Crashes with pull-to-refresh on old versions of Android

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/RedReader#498]
Reported here:

https://www.reddit.com/r/RedReader/comments/6b3qsy/version_198_released/dhmbrwb/

> when I swipe down to refresh (either in the post view or in the comments view) RedReader crashes. That doesn't happen when I use the refresh button though. And it used to work just fine in the previous version. This only seems to happen on my older phone using Android 4.0.

Looks like more testing is needed on older Android versions :)

**Comment by ithil** [comment]
Thank you for looking into it! :) I also just found the crash log on my phone:

```
java.lang.NullPointerException
	at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
	at android.widget.ImageView.onDraw(ImageView.java:910)
	at android.view.View.draw(View.java:11050)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
	at android.view.View.draw(View.java:11053)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
	at android.view.View.draw(View.java:11053)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2885)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
	at android.view.View.draw(View.java:11053)
	at android.widget.FrameLayout.draw(FrameLayout.java:450)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4248)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
	at android.view.View.draw(View.java:11053)
	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
	at android.view.View.draw(View.java:11053)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2887)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
	at android.view.View.getDisplayList(View.java:10487)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2597)
	at android.view.View.getDisplayList(View.java:10452)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:873)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:1914)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1638)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2452)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by philipwhiuk** [comment]
StackOverflow answer gives some advice: http://stackoverflow.com/questions/26375001/android-java-lang-nullpointerexception-at-android-view-gles20recordingcanvas-dr

**Comment by itmike** [comment]
I have nothing to add except Nexus 6p is also affected by this. Stock android, only OTA updates from google. Redreader from fdroid.

Atleast the app restarts with the subreddit I was reading.

**Comment by QuantumBadger** [comment]
This doesn't seem to be an issue any more, please re-open if you see it again!
