### ISSUE TITLE
Java error upon running the app

### ISSUE THREAD

**Issue by codingJWilliams** [QuantumBadger/RedReader#595]
I've followed your BUILD.MD guide and got the project set up and installed. I get this error through Logcat when I run the app on my phone, either using the Run button or by copying over the apk, installing it, and running it manually
```
05-07 17:43:16.147 29305-29305/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.quantumbadger.redreader, PID: 29305
    java.lang.RuntimeException: Unable to instantiate application org.quantumbadger.redreader.RedReader: java.lang.ClassNotFoundException: Didn't find class "org.quantumbadger.redreader.RedReader" on path: DexPathList[[zip file "/data/app/org.quantumbadger.redreader-2/base.apk"],nativeLibraryDirectories=[/data/app/org.quantumbadger.redreader-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:855)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5708)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6605)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.quantumbadger.redreader.RedReader" on path: DexPathList[[zip file "/data/app/org.quantumbadger.redreader-2/base.apk"],nativeLibraryDirectories=[/data/app/org.quantumbadger.redreader-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5708) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6605) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889) 
05-07 17:43:25.424 18433-18453/? E/HwLauncher: Model Exception :item: ShortcutInfo(title=RedReader)modelItem: nullError: ItemInfo passed to updateIsNewInstalled doesn't match original
05-07 17:43:25.755 29542-29542/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.quantumbadger.redreader, PID: 29542
    java.lang.RuntimeException: Unable to instantiate application org.quantumbadger.redreader.RedReader: java.lang.ClassNotFoundException: Didn't find class "org.quantumbadger.redreader.RedReader" on path: DexPathList[[zip file "/data/app/org.quantumbadger.redreader-2/base.apk"],nativeLibraryDirectories=[/data/app/org.quantumbadger.redreader-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:855)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5708)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6605)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.quantumbadger.redreader.RedReader" on path: DexPathList[[zip file "/data/app/org.quantumbadger.redreader-2/base.apk"],nativeLibraryDirectories=[/data/app/org.quantumbadger.redreader-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5708) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1643) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6605) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:999) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:889) 
```

**Comment by codingJWilliams** [comment]
Oh it either fixed itself or my messing around fixed it, nvm
