### ISSUE TITLE
"Share Image" throws error on Android 8.1+ from master branch builds

### ISSUE THREAD

**Issue by LizardWithHat** [QuantumBadger/RedReader#627]
I tried to work on an other issue when this came up.

**Issue:** On emulators with Android 8.1 and up, sharing an image via the context menu throws an exception on builds from the master branch. The image gets downloaded like expected, but enters the "mail the error" screen instead of opening the share menu.

**Steps to reproduce:** 

1. Checkout master branch and build/run RedReader on a device with Android version >= 8.1
2. Long press on any image post
3. Choose "Share Image"
4. The Application correctly asks for permissions, allow
5. Error Page should show up now

I got this fixed by using the method from [this](https://stackoverflow.com/a/50265329) stackoverflow thread in the ImageCallback class. The answer mentions this is a problem for API levels 24 and up, though Android 7.1 (25) works as expected.
However, before just putting the pull request up, I think it would be great if other people, maybe with real devices, can confirm this and how to properly tackle the issue if it's confirmed.

This is the relevant part of the LogCat:
```
2018-10-20 21:48:58.528 5662-5787/org.quantumbadger.redreader E/CacheRequest: Exception thrown by onSuccess
    android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/jELlOQf.mp4 exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
        at android.net.Uri.checkFileUriExposed(Uri.java:2348)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9854)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9860)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9839)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4487)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4445)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4806)
        at android.app.Activity.startActivity(Activity.java:4774)
        at org.quantumbadger.redreader.image.ShareImageCallback$1$1.onSuccess(ShareImageCallback.java:152)
        at org.quantumbadger.redreader.cache.CacheRequest.notifySuccess(CacheRequest.java:231)
        at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread$1.run(CacheManager.java:491)
        at org.quantumbadger.redreader.common.PrioritisedCachedThreadPool$Executor.run(PrioritisedCachedThreadPool.java:104)
        at java.lang.Thread.run(Thread.java:764)
2018-10-20 21:48:58.559 5662-5787/org.quantumbadger.redreader E/BugReportActivity: Handling exception
    android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/jELlOQf.mp4 exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
        at android.net.Uri.checkFileUriExposed(Uri.java:2348)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9854)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9860)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9839)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4487)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4445)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4806)
        at android.app.Activity.startActivity(Activity.java:4774)
        at org.quantumbadger.redreader.image.ShareImageCallback$1$1.onSuccess(ShareImageCallback.java:152)
        at org.quantumbadger.redreader.cache.CacheRequest.notifySuccess(CacheRequest.java:231)
        at org.quantumbadger.redreader.cache.CacheManager$RequestHandlerThread$1.run(CacheManager.java:491)
        at org.quantumbadger.redreader.common.PrioritisedCachedThreadPool$Executor.run(PrioritisedCachedThreadPool.java:104)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by QuantumBadger** [comment]
I'm happy to merge in your fix if it works in the emulator :)
