### ISSUE TITLE
Crash due to missing drawable ic_accounts_dark.xml (Proguard issue)

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/RedReader#884]
Crashes when opening the three-dots context menu:

```
--------- beginning of crash
07-11 13:57:52.174  9395  9395 E AndroidRuntime: FATAL EXCEPTION: main
07-11 13:57:52.174  9395  9395 E AndroidRuntime: Process: org.quantumbadger.redreaderalpha, PID: 9395
07-11 13:57:52.174  9395  9395 E AndroidRuntime: android.content.res.Resources$NotFoundException: Drawable org.quantumbadger.redreaderalpha:drawable/ic_accounts_dark with resource ID #0x7f0800c4
07-11 13:57:52.174  9395  9395 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable-anydpi-v21/ic_accounts_dark.xml from drawable resource ID #0x7f0800c4
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:827)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.content.Context.getDrawable(Context.java:635)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:2)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:9)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:1)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:1)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:6)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.ListMenuItemView.initialize(ListMenuItemView.java:7)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuAdapter.getView(MenuAdapter.java:11)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:6)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:19)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:12)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:3)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at androidx.appcompat.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:8)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: Caused by: android.view.InflateException: Class not found x
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:222)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:139)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	... 23 more
07-11 13:57:52.174  9395  9395 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "x" on path: DexPathList[[zip file "/data/app/org.quantumbadger.redreaderalpha-nZTPMGwTYm1RdMJqyrA3Bg==/base.apk"],nativeLibraryDirectories=[/data/app/org.quantumbadger.redreaderalpha-nZTPMGwTYm1RdMJqyrA3Bg==/lib/arm64, /data/app/org.quantumbadger.redreaderalpha-nZTPMGwTYm1RdMJqyrA3Bg==/base.apk!/lib/arm64-v8a, /system/lib64]]
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:203)
07-11 13:57:52.174  9395  9395 E AndroidRuntime: 	... 27 more
07-11 13:57:52.178  1579  4516 W ActivityManager:   Force finishing activity org.quantumbadger.redreaderalpha/.activities.PostListingActivity
```

**Comment by QuantumBadger** [comment]
Resolved in Alpha 289.
